dist: xenial
sudo: required
language: cpp
os: linux
compiler: gcc
env:
- TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code && make
